# Data sources

We used three main sources for the data in this research project. 

- We use the Robintrack [website](https://robintrack.net/data-download) to get the ownership data from Robinhood. This data is pulled from the Robinhood API which provides this data for free to the world. It provides a csv file for each ticker and documents the number of unique accounts holding at least one share of the stock from May 2018 to August 2020. As per the source, the data was collected from the Robinhood API once per hour.  We will refer to the number of unique accounts holding at least one share of the stock as "ownership" and is a indicator of a stock's "popularity" among Robinhood users. This only includes accounts that have normal long shares and do not impact any impacts from options. Note as publicly disclosed on various news articles, Robinhood stopped making this information public in August 2020 so our dataset ends in 8/1/2020. 

- In addition, we scrapped Yahoo Finance to get the stock price and trading volume of each company during the corresponding time period.  As we will expand on in the "Missing Data" section, we discovered that Yahoo Finance has some bugs where it does not have information over a certain periods of time for certain companies but these glitches were few and far in-between. 

- Lastly, we pulled the market capitalization of all the companies in the S&P500, daily VIX and companies characteristics from Bloomberg during the relevant time period. Both Yahoo Finance and Bloomberg are credited sources commonly used in the finance industry. 
