# Conclusion

In conclusion, we examined Robinhood user data to see how have investment preference for retail investors change over time on the platform. Using the number of accounts who owned the stock as a proxy for popularity, we explored the data looking at individual companies and company characteristics. Further areas of exploration can include looking at stocks outside of the S&P500 index and over different time periods. Anecdoctally, news articles have mentioned companies such as Tesla that were out of scope for this analysis, as potentially popular stocks with Robinhood users with noteworthy pattern. Unfortunately this Robinhood data was ceased to be available to the public in August 2020 as it would be interesting to apply our methodology over data from the last few months to observe more recent trends. Given the number of accounts on the entire Robinhood platform continued to increase since August 2020, having access to more recent data would provide more data points and leave room for future analysis.

